# Generated by Django 3.1.7 on 2021-03-18 09:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.FileField(default=None, null=True, upload_to='publish/%Y/%m/%d/thumbnail')),
                ('gif', models.FileField(default=None, null=True, upload_to='publish/gifs/%Y/%m/%d/video')),
                ('video_file', models.FileField(default=None, null=True, upload_to='publish/%Y/%m/%d/video')),
                ('published_at', models.DateTimeField(blank=True, default=datetime.datetime.utcnow, null=True)),
                ('description', models.TextField(null=True)),
                ('duration', models.TimeField(default=datetime.datetime.utcnow, null=True)),
                ('is_published', models.BooleanField(blank=True, default=False, null=True)),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True)),
                ('is_published', models.BooleanField(blank=True, default=False, null=True)),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.FileField(default=None, null=True, upload_to='saved/%Y/%m/%d/thumbnail')),
                ('gif', models.FileField(default=None, null=True, upload_to='saved/gifs/%Y/%m/%d/video')),
                ('video_file', models.FileField(default=None, null=True, upload_to='saved/%Y/%m/%d/video')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.utcnow, null=True)),
                ('description', models.TextField(null=True)),
                ('duration', models.TimeField(default=datetime.datetime.utcnow, null=True)),
                ('bg_musicfile', models.FileField(default=None, null=True, upload_to='saved/bgms/%Y/%m/%d/video')),
                ('published_video_details', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='videos.publishedvideo')),
            ],
        ),
        migrations.CreateModel(
            name='Scenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1, null=True)),
                ('title', models.TextField(blank=True, default='', null=True)),
                ('animation', models.CharField(blank=True, max_length=200, null=True)),
                ('narration', models.FileField(default=None, null=True, upload_to='saved/narrations/%Y/%m/%d/video')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.savedvideo')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alignment', models.CharField(choices=[('Left', 'left'), ('Right', 'right')], max_length=6)),
                ('font_color', models.CharField(max_length=6)),
                ('background_color', models.CharField(max_length=6)),
                ('text_position', models.CharField(choices=[('Top', 'top'), ('Center', 'center'), ('Bottom', 'bottom')], max_length=10)),
                ('text', models.TextField(blank=True, default='', null=True)),
                ('font_style', models.CharField(max_length=50)),
                ('font_size', models.IntegerField()),
                ('font_type', models.CharField(max_length=50)),
                ('scene', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='videos.scenes')),
            ],
        ),
        migrations.AddField(
            model_name='savedvideo',
            name='tags',
            field=models.ManyToManyField(to='videos.Tags'),
        ),
        migrations.AddField(
            model_name='savedvideo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publishedvideo',
            name='tags',
            field=models.ManyToManyField(to='videos.Tags'),
        ),
        migrations.AddField(
            model_name='publishedvideo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Upload', 'upload'), ('Library', 'library')], max_length=10)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='scenes/user_uploaded_video/%Y/%m/%d')),
                ('item_duration', models.TimeField(default=datetime.datetime.utcnow, null=True)),
                ('scene', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='videos.scenes')),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_text', models.CharField(max_length=25)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.scenes')),
            ],
        ),
    ]
