# Generated by Django 3.1.7 on 2021-03-13 08:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('temp_file', models.FileField(upload_to='temporary/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('thumbnail', models.FileField(default=None, null=True, upload_to='publish/%Y/%m/%d/thumbnail')),
                ('video', models.FileField(default=None, null=True, upload_to='publish/%Y/%m/%d/video')),
                ('script', models.TextField(null=True)),
                ('topic', models.CharField(default='Education', max_length=100, null=True)),
                ('rating', models.FloatField(default=0.0, null=True)),
                ('publish_time', models.DateTimeField(blank=True, default=datetime.datetime.utcnow, null=True)),
                ('is_save_later', models.BooleanField(blank=True, default=False, null=True)),
                ('publised_video_id', models.IntegerField(default=None, null=True)),
                ('language', models.CharField(default='en', max_length=5, null=True)),
                ('duration', models.TimeField(default=datetime.datetime.utcnow, null=True)),
                ('background_music_file', models.FileField(blank=True, default=None, null=True, upload_to='publish/%Y/%m/%d/bgm')),
                ('background_music_url', models.URLField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=200, null=True)),
                ('videos', models.ManyToManyField(to='videos.Video')),
            ],
        ),
        migrations.CreateModel(
            name='Scenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1, null=True)),
                ('video_url', models.URLField(blank=True, default=None, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='scenes/user_uploaded_video/%Y/%m/%d')),
                ('text', models.TextField(blank=True, default='', null=True)),
                ('keywords', models.TextField(blank=True, default='', null=True)),
                ('font_color', models.CharField(blank=True, default='#000000', max_length=10, null=True)),
                ('background_color', models.CharField(blank=True, default='#ffffff', max_length=10, null=True)),
                ('text_position', models.CharField(blank=True, default='bottom', max_length=10, null=True)),
                ('narration', models.FileField(blank=True, null=True, upload_to='scenes/user_uploaded_narration/%Y/%m/%d')),
                ('video', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
        ),
    ]
