# Generated by Django 3.1.7 on 2021-03-18 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenes',
            name='tags',
            field=models.ManyToManyField(to='videos.Tags'),
        ),
        migrations.AlterField(
            model_name='savedvideo',
            name='published_video_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='videos.publishedvideo'),
        ),
        migrations.DeleteModel(
            name='Keywords',
        ),
    ]
