# Generated by Django 3.1.7 on 2021-03-20 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20210319_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='scene',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='videos.scenes'),
        ),
        migrations.AlterField(
            model_name='media',
            name='animation',
            field=models.CharField(choices=[('None', 'none'), ('Zoom In', 'zoom in'), ('Zoom Out', 'zoom out')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='publishedvideo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='videos.Tags'),
        ),
        migrations.AlterField(
            model_name='savedvideo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='videos.Tags'),
        ),
        migrations.AlterField(
            model_name='scenes',
            name='tags',
            field=models.ManyToManyField(blank=True, to='videos.Tags'),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='background_color',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='font_color',
            field=models.CharField(max_length=7),
        ),
    ]
