# Generated by Django 3.1.7 on 2021-03-13 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        ('transacaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buymodel',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.video'),
        ),
    ]
